name: Build Docker Image

on:
  push:

env:
  IMAGE_NAME: ctour

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@master

      - name: Log into Docker Hub
        uses: docker/login-action@master
        with:
          username: zxilly
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into GitHub Package
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Release metadata
        id: meta
        uses: docker/metadata-action@master
        with:
          tags: |
            type=ref,event=branch
          images: zxilly/${{ env.IMAGE_NAME }},ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push Release Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
